OmeSatoFoundation/ome-doc

03/contents/chap03_02_2_15.tex

p.16 in text 03 contains a tcolorbox across the page but overflowed contents are not shown. Appending an option of breakable let the box be across a page.
TODO: all the tcolorbox-es should be breakable.
TODO: tcolorbox closes at the end of every page break even another contents continue; we expect the bottom or top of the box should be open to suggest that it continues on the other pages.

corresponding tcolorbox is set to breakable.

---

01/llmk.toml
07/llmk.toml
08/llmk.toml
Dockerfile

PDF への変換は `dvipdfmx` が前提のところ，誤って `dvipdfm` が指定されていたため修正した．
See related issue at https://github.com/OmeSatoFoundation/ome-doc/issues/121

use dvipdfmx instead of dvipdfm

---

03/contents/chap03_03_3.tex

Close #113;
ソースコードでは `geti2c_lux_init` で照度センサを初期化していた
一方、説明文では `init_lux` を説明していたため、
説明文で `geti2c_lux_init` を説明するよう修正。

照度センサ初期化関数を修正

---

03/llmk.toml
05/llmk.toml
06/llmk.toml

llmk.toml内でlualatexのオプション指定を`command`内ではなく、`opt`アトリビュートを使う用に変更。

[第3回] [第5回] [第6回] llmk.toml内でlualatexのオプション指定にoptアトリビュートを使うように変更

---

01/contents/chap01_02.tex
01/contents/chap01_preamble.tex

fix #133 
「
P.16　どの文が例題なのか分からない。
ここでは、P.17の「Documents フォルダ直下に taro 、 hanako 、 saburo という名前のフォルダを作成しましょう。」が例題と思われるが、このセクション全体が「例題」となっている。セクション名を「フォルダの操作」など、具体的なものに変更し、実際に子どもたちが作業する例題部分を明示すること
セクションは操作の名前、セクション中に、操作の説明を記述。例題として、子どもたちが自分で行う操作を答え付きで示す
」
に対応
UI色のサブセクションが例題のみで、問題がなかったため、問題を追加
ユーザ名注意喚起の説明を修正、パスに関しての説明が第3回であるようなので、ここでは説明しない

適切なサブセクションの設定

---

01/contents/chap01_04.tex

4章の、/usr/local/ome/shareから、教材をコピーする手順を例題として設定する。
シールカードを用いた進捗管理を考慮した変更。

教材コピー手順を例題として設定

---

01/contents/chap01_preamble.tex

\usepackage{enumitem}
が、#206 において、chap01_01.texのみに適用されていたため、マージ時に削除し、プリアンブルファイルに追加

不足パッケージの追加

---

01/contents/chap01_01.tex
01/contents/chap01_02.tex
01/contents/chap01_preamble.tex

fix #208 
会津大作成のマクロをベースに、スペース要件を満たした解答欄を生成可能にした。
この変更にあたって、Wi-Fi設定の問題内容に一部変更を行った。変更前は、Wi-Fiアドレスとパスワードの例が記されていたが、レイアウトの都合上省いた。これに関するissue #178 では、「当日、TAからWiFiアクセスポイントとパスワードを各グループごとに指定するので、TAから聞いたアクセスポイントとパスワードをテキストにメモを取らせてください。（課題として追加）」と先生がおっしゃっているので、記入欄だけ確保すれば最低要件は満たしていると考えたため、Wi-Fiアドレスとパスワードの例は削除した。
変更後

空欄を伴う問題について、空欄の高さを統一

---

Dockerfile
texmf/tex/luatexja/omebook/omebook.sty

omebookをGoogle Fontsで公開されているモリサワbiz ud 明朝とゴシックに対応させました。
LaTeX用Dockerの再ビルド（かフォントを自分で無理やり入れる）が必要です。

bizudフォントの対応

---

03/contents/chap03_02_2_8.tex

[第3回] Typo修正

---

03/contents/chap03_01.tex

Closes #261 again.
1) prohibit page break in listings
2) position the comment to the caption from inside the code block

improve appearance in ls command explanation

---

07/text07.tex
08/text08.tex

closes #290
closes #348 
- #148 のカウンタ設定マクロを用いて第７，８回の例題と問題にカウンタを設定した。また、例題設定以後に例題番号を参照するものはラベリングした。
- 上記と同様にカウンタ、ラベルを設定した。
- 問題8-20,23,25,27,29 -> 例題8-10,11,12,13,14

第７，８回 例題問題番号のカウンタ設定、一部問題に変更

---

05/contents/chap05_03_3.tex
05/contents/chap05_03_4.tex
05/slide_contents/digital_input_device.tex
05/slide_contents/ir.tex

修正内容
- スライドの入れ替わっていたスイッチとリミットスイッチの画像を正す
- テキストとスライドのdigin.hspのLEDのGPIO番号を17から23にする (#355 )
- テキストの「 アナログ入力装置を使ってみよう」の説明文の修正
- スライドのlircdコマンドのタイポを修正
- スライドの「風船機」を「扇風機」に修正

第5回のスライドとテキストの微修正

---

08/slide08-2.tex

2時間目のスライドのasciiコード表の参照をつけ忘れていたのを修正
[slide08-2.pdf](https://github.com/OmeSatoFoundation/ome-doc/files/12668656/slide08-2.pdf)

第8回スライド minor fix

---

03/contents/chap03_03_6.tex

インデントがtabによって整えられていたため、このようなインデントずれが起きていた。spaceを使用して調節した。

第3回 ソースコード中のインデント幅を調整した(Fix #262)

---

06/contents/chap06_05_5.tex

リスト6.8のcaptionが`ledvoice.hsp`となっていたのを`ledbyvoice.hsp`と修正した。

［第6回］リスト6.8 文字訂正(Fix #358)

---

Dockerfile

Current Dockerfile fetches the latest of texlive and does not replicate typeset environments at that time; in that case `lualatex` causes an error related to `\setmainjfont`:
```
PS G:\ome-doc> docker run --rm -v ${pwd}:/workdir -ti ome-doc sh -c 'cd 03 ; llmk'
(Omitted)
(/usr/local/texlive/2024/texmf-dist/tex/luatex/luatexja/addons/luatexja-fontspe
c-27c.sty))
! Undefined control sequence.
\__ltj_fontspec_setup_single_size:nnn ...nown:nxN
{fontspec-sizing}{\exp_aft...
l.27 \setmainjfont
[Ligatures={Common,TeX},
? X
733 words of node memory still in use:
6 hlist, 4 rule, 1 dir, 3 kern, 1 glyph, 116 attribute, 49 glue_spec, 18 att
ribute_list, 1 if_stack, 1 write, 8 user_defined nodes
avail lists: 1:4,2:121,3:3,4:4,5:2,6:1,7:7,9:8
warning  (pdf backend): no pages of output.
Transcript …
```

Fix the version of 2023 for texlive

---

03/text03.tex

text03.tex内で読み込んでいるtexファイルの名称がcontentsディレクトリ下に存在するファイルの名称と一致していない為にタイプセットが出来なかった。
このcommitではtext03.tex内で指定しているファイルの名称を修正することでタイプセットができるようにした。

[第3回] 教科書がタイプセットが出来ない不具合の修正

---

03/contents/chap03_310_AdvancedCommands.tex

- wc: 結果を変更
- seq: 行するディレクトリをhomeに変更
- echo: 同上
- touch: lsのオプションを変更
- lsの出力をリダイレクトする: cat lsfileの出力結果の末尾にtesttouchを追加
- cat: コマンドにリダイレクトでファイルを入力する: cat < lsfile の出力結果の末尾にtesttouchを追加
- lsコマンドの出力をパイプでlessコマンドに渡す: リストを一つ追加し、lessの実行結果を記述
- tac: 出力結果の先頭にtesttouchを追加
- shuf: 出力結果にtesttouchを追加
- tail: 出力結果の先頭のVIdeoを削除し、末尾にtesttouchを追加
- sort: 実行結果の末尾にtesttouchを追加
- パイプラインを用いたsortコマンドの実行: 表示するディレクトリをhomeに変更
- touchの説明: ls のオプションをaからlに変更
- パイプラインを用いたsortコマンドの実行: 説明の~03をhomeディレクトリに変更

【第3回】リスト3.19から3.43の修正

---

03/contents/chap03_110_Terminal.tex
03/contents/chap03_310_AdvancedCommands.tex

#565  について以下を修正
- p2, リスト3.1の先頭のスペースを削除
- p36, 問題3-11-1, 「~/02」から「ホームディレクトリ」に置き換え
- p44, 下から２行目,「home ディレクトリ」から「ホームディレクトリ」へ表現を統一
- p45, 問題3-13-5, 対象のディレクトリを02から03へ変更

#565 の一部の修正

---

03/images/chap03/directory_relation.svg
03/slide03.tex
03/slide_contents/advanced_command.tex
03/slide_contents/sensorboard.tex
03/slide_contents/shell_command.tex

#576 
* 3章で使うファイルのコピー方法
* コマンド履歴
* ディレクトリの上下関係
* LEDをチカチカさせよう
* 空のファイルを作る(touchコマンド)
* findコマンドでファイルを探す
* 複数ファイルの指定
* ワイルドカード
* ターミナルで困ったときの対応
* コマンドの検索
* コマンド中のファイルやディレクトリなどに下線を追加
* 複数ファイル指定できるものに三点リーダーを追加
* 問題番号・ページ数
* スライドの入れ替え

第3回 授業スライド調整

---

06/contents/chap06_04_3.tex

diff
`2023年8月20日` -> `2024年9月21日`
第6回の講義が9/21(土)に行われると考えこの変更を加えたが，もしそうでなければ再更新

【第６回】gettimeの実行例の更新

---

06/contents/chap06_01.tex
06/contents/chap06_04_1.tex
06/contents/chap06_04_2.tex
06/contents/chap06_04_3.tex
06/contents/chap06_04_4.tex
06/contents/chap06_05_2.tex
06/contents/chap06_05_3.tex
06/contents/chap06_05_4.tex
06/contents/chap06_05_5.tex
06/slide06.tex

- ディレクトリをコピーするとき06から07に名前を変更するように明記した
- ターミナルを用いた教材のコピー方法を追加した
- 06ディレクトリを参照していた箇所を07参照にした
- 06ディレクトリを参照していた箇所を07参照にした
- スライドで06ディレクトリの名前を07に変更するするように指示するスライドがない
close #648

【第６回】ディレクトリのコピー先を06から07にする

---

.github/workflows/build-image.yml

This commit enables you to pull container image that perform typesetting. 
To do so, navigate to Packages page in the project. https://github.com/orgs/OmeSatoFoundation/packages?repo_name=ome-doc
Then click a package name and you will see a command to pull the container. e.g.,
```bash
$ docker pull ghcr.io/omesatofoundation/ome-doc/ome-doc:workflow-dev
```
This feature wonderfully saves time to build container images in local computers, which includes texlive installation.

Add GitHub Workflow to build & push container image into github container registory
