03/llmk.toml
05/llmk.toml
06/llmk.toml

add `--cnf-line` to avoid platform-dependent TEXINPUTS

---

tools/kanjicheck.py

kanji check tool

---

03/contents/chap03_02_2_13.tex

slideshow.gif をひらくときの cwd を考慮する

---

01/contents/chap01_01.tex
01/contents/chap01_02.tex
01/contents/chap01_03.tex
01/contents/chap01_04.tex
01/contents/chap01_05.tex
01/contents/chap01_07.tex
01/contents/chap01_08.tex
01/contents/chap01_preamble.tex

Figureを削除し、図に変更

---

01/contents/chap01_02.tex
01/contents/chap01_03.tex
01/contents/chap01_04.tex
01/contents/chap01_07.tex

はみ出している部分といらない空白を修正

---

03/contents/chap03_03_3.tex

Issue #1 に提案されていた修正案
- P.29 問題3-2-3 初期化の命令もあったほうがよい？（初期化をしないと使えないため）
-> 初期化の命令を回答させる欄を追記した。

[第3回] Issue #1で提案された修正案の一部を反映

---

tools/kanjicheck.py

会議で指摘された、ルビ振りのチェックを行えるようにスクリプトを修正しました

ルビ\rubyでルビが振られた箇所をスキップするように対応

---

tools/kanjicheck.py

漢字スクリプトの規定以上の漢字の検出を、初回登場時のみ出力するよう変更

漢字スクリプトの検出を初回登場時のみに変更

---

01/contents/chap01_01.tex

ルビ振りをミスしている箇所の修正

---

01/Makefile

for ome-doc/01, add Makefile to generate pdf and screen pdf.

add Makefile

---

03/contents/chap03_01.tex
03/contents/chap03_02_2_10.tex
03/contents/chap03_02_2_11.tex
03/contents/chap03_02_2_12.tex
03/contents/chap03_02_2_3.tex
03/contents/chap03_02_2_5.tex
03/contents/chap03_02_2_6.tex
03/contents/chap03_02_2_7.tex
03/contents/chap03_02_2_8.tex
03/contents/chap03_02_2_9.tex

新しいコマンド説明のタイトルをタイプライタ型に変更しました。

第３回 typewriter型に変更

---

03/contents/chap03_02_2_9.tex

leafpadをmousepadに変更

---

03/contents/chap03_01.tex

問題3-2, 3-4での付け忘れたaddquizマクロの追加

[第3回] 付け忘れたaddquizマクロの追加

---

03/text03.tex
05/text05.tex
06/text06.tex
texmf/tex/luatexja/omebook/omebook.sty

第六回の body font size を 12 pt に

---

08/text08.tex

第8回 leafppad->mousepad

---

07/text07.tex

[第７回]  「raspberry pi」をラズパイの表記に統一

---

07/text07.tex

第７回　画像のコピーに関する説明を追記

---

07/text07.tex

#370
p22 問題7-6の問題文中の"host" 表記を　"dig" 表記に変更

digコマンドに関する変更

---

07/text07.tex

例題7-3を見てみましょうのような表現をlabelを使用したものに変更。
closes #290

[第７回] labelを追加

---

07/text07.tex

#395 解説スクリプトに行数を明記、それに伴う文中の番号を変更した。

[7回] 行数の明記とそれに伴う文中の番号の変更

---

07/text07.tex

[第７回]  画像をコピーするコマンドを追加

---

03/contents/chap03_02_2_6.tex

Close #459, close #460

---

03/contents/chap03_03_6.tex

誤字の修正 #310

---

03/text03.tex

構造変更を反映 #479

---

05/contents/chap05_04_5.tex

赤外線受信用デバイスファイルの変更を行った。
スライドは修正済みであった。

[第5回] 赤外線送受信のまとめの修正

---

06/slide06.tex

スライド15枚目を編集しました。
https://github.com/OmeSatoFoundation/ome-doc/issues/357
このissueに関するものです。

slide06 問題6-4の説明を追加

---

03/slide03.tex
03/slide_contents/title.tex

The changes enables any viewers to open the output PDF by resolving generation of an empty PDF.

add a title slide for 03

---

01/llmk.toml

第1回のtomlファイルを変更

---

05/contents/chap05_04_3.tex
05/contents/ir_notice.tex
05/text05.tex

IR ロボットに関する注記を追加

---

03/slide_contents/shell_command.tex

slide03前半作成途中

---

03/contents/chap03_150_AdvancedCommands.tex

echoコマンドの説明を追加

---

03/slide_contents/sensorboard.tex

スライド21ページとスライド36ページを追記
https://github.com/OmeSatoFoundation/ome-doc/issues/496

第3回 スライド 細かい修正

---

03/slide_contents/shell_command.tex

第3回コマンドの応用のスライド追加

---

03/slide_contents/sensorboard.tex

#536 
センサーボードの画像の出典をスライドの最後に追記しました

第３回授業スライド センサーボード画像の出典追記

---

03/contents/chap03_320_PipeAndRedirect.tex

sed コマンドを使った例
Hi, Wowld 　->　Hi, World
に修正

第3回　p51 スペルミスを修正

---

03/contents/chap03_140_Commands02.tex
03/contents/chap03_310_AdvancedCommands.tex
03/contents/chap03_320_PipeAndRedirect.tex

#568 
該当箇所すべてをsyousetu.txt に修正しました

第3回 syousetuスペルの修正

---

03/contents/chap03_320_PipeAndRedirect.tex

- issue 571についてのpull requestです
close #571

xargsオプションpの説明、ワイルドカードの丁寧語の改善

---

03/slide03.tex
03/slide_contents/advanced_command.tex
03/slide_contents/sensorboard.tex
03/slide_contents/shell_command.tex
03/slide_contents/title.tex

スタイルの変更。コマンド定義の統一。その他種々の変更。

---

03/slide_contents/advanced_command.tex

576 adj slide

---

05/contents/chap05_01.tex
05/contents/chap05_03_2.tex

- 5-1-2`車に使われているセンサー...`を`スマートフォンに使われているセンサー...`に直した
- `gpio GPIO ピン番号,0 でブリックをON にします。`,`gpio GPIO ピン番号,1 でブリックをOFF にします。`のon,offを訂正した
close #590

第5回 前半の教科書修正

---

06/slide06.tex

close #595 
スタイルを第３回のスライドと同じものに変更

第６回 授業スライド スタイル変更

---

05/slide05.tex
05/slide_contents/digital_input_device.tex
05/slide_contents/exe.tex

close #593
* スタイルを第３回の授業スライドと同じものに変更
* スライド28 センサーをピンにつけてみよう
HSP で digout.hsp を動かしてみよう -> HSP で digin.hsp を動かしてみよう
* スライド80 
作りたいものを考えよ -> 作りたいものを考えよう

第５回 授業スライド スタイル変更

---

cards/cards.tex

第5回と第7回のシールカードです。
第5回　問題 14問
第7回　例題 12問
　　　  問題 15問

第5回、第7回 シールカード

---

cards/cards.tex

第6回、第8回シールカード

---

06/slide06.tex

第６回　授業スライド調整

---

06/contents/chap06_05_5.tex

Closes https://github.com/OmeSatoFoundation/ome-doc/issues/637

fix typo in ledbyvoice.hsp

---

05/contents/chap05_03_2.tex

https://github.com/OmeSatoFoundation/ome-doc/issues/625#issuecomment-2955035341 を修正.

minor fix 05 contents

---

06/slide06.tex

add another slide to describe copying and renaming the 06 material into 07

---

05/contents/chap05_03_7.tex

【第五回】節5.12のタイトル変更
